#!/bin/zsh

alias git_my_branches="git for-each-ref --sort=committerdate refs/heads/ --format='%(HEAD) %(color:yellow)%(refname:short)%(color:reset) - %(color:red)%(objectname:short)%(color:reset) - %(contents:subject) - %(authorname) (%(color:green)%(committerdate:relative)%(color:reset))'"

local selected_branch=$(git_my_branches --color | fzf --ansi --tac | awk '{print $1}')
if [ "$selected_branch" != '*' ]; then
          git checkout $selected_branch
fi


